USE [master]
GO
/****** Object:  Database [PSAT_Dev]    Script Date: 17-09-2023 23:03:13 ******/
CREATE DATABASE [PSAT_Dev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PSAT_Dev', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PSAT_Dev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PSAT_Dev_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PSAT_Dev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PSAT_Dev] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PSAT_Dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PSAT_Dev] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PSAT_Dev] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PSAT_Dev] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PSAT_Dev] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PSAT_Dev] SET ARITHABORT OFF 
GO
ALTER DATABASE [PSAT_Dev] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PSAT_Dev] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PSAT_Dev] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PSAT_Dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PSAT_Dev] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PSAT_Dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PSAT_Dev] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PSAT_Dev] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PSAT_Dev] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PSAT_Dev] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PSAT_Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PSAT_Dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PSAT_Dev] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PSAT_Dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PSAT_Dev] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PSAT_Dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PSAT_Dev] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PSAT_Dev] SET RECOVERY FULL 
GO
ALTER DATABASE [PSAT_Dev] SET  MULTI_USER 
GO
ALTER DATABASE [PSAT_Dev] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PSAT_Dev] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PSAT_Dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PSAT_Dev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PSAT_Dev] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PSAT_Dev] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PSAT_Dev', N'ON'
GO
ALTER DATABASE [PSAT_Dev] SET QUERY_STORE = OFF
GO
USE [PSAT_Dev]
GO
/****** Object:  Table [dbo].[Project]    Script Date: 17-09-2023 23:03:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Project](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[Description] [varchar](300) NULL,
	[IsDestroyed] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CreatedBy] [uniqueidentifier] NOT NULL,
	[ModifiedBy] [uniqueidentifier] NULL,
	[ModifiedDate] [datetime] NULL,
	[ProjectTechnologyId] [uniqueidentifier] NOT NULL,
	[ProjectTypeId] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProjectTechnology]    Script Date: 17-09-2023 23:03:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProjectTechnology](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[IsDestroyed] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CreatedBy] [uniqueidentifier] NOT NULL,
	[ModifiedBy] [uniqueidentifier] NULL,
	[ModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_ProjectTechnology] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProjectType]    Script Date: 17-09-2023 23:03:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProjectType](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[IsDestroyed] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CreatedBy] [uniqueidentifier] NOT NULL,
	[ModifiedBy] [uniqueidentifier] NULL,
	[ModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_ProjectType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[ProjectType] ([Id], [Name], [IsDestroyed], [CreatedDate], [CreatedBy], [ModifiedBy], [ModifiedDate]) VALUES (N'50087a29-6d6c-441d-a8a5-0ce7a3ec3934', N'Ecommerce', 0, CAST(N'2023-09-17T21:03:45.337' AS DateTime), N'4c18f822-c9dc-492b-8089-b4fbefe5a843', N'4c18f822-c9dc-492b-8089-b4fbefe5a843', CAST(N'2023-09-17T21:04:04.793' AS DateTime))
GO
INSERT [dbo].[ProjectType] ([Id], [Name], [IsDestroyed], [CreatedDate], [CreatedBy], [ModifiedBy], [ModifiedDate]) VALUES (N'6096b232-a849-4985-8fbf-61e29f805ebe', N'Insurance', 0, CAST(N'2023-09-17T22:12:13.340' AS DateTime), N'00000000-0000-0000-0000-000000000000', NULL, NULL)
GO
/****** Object:  Index [IX_Project]    Script Date: 17-09-2023 23:03:15 ******/
CREATE NONCLUSTERED INDEX [IX_Project] ON [dbo].[Project]
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ProjectTechnology] ADD  CONSTRAINT [DF_ProjectTechnology_Id]  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[ProjectType] ADD  CONSTRAINT [DF_ProjectType_Id]  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[ProjectType] ADD  CONSTRAINT [DF_ProjectType_IsDestroyed]  DEFAULT ((0)) FOR [IsDestroyed]
GO
ALTER TABLE [dbo].[Project]  WITH CHECK ADD  CONSTRAINT [FK_Project_ProjectTechnology] FOREIGN KEY([ProjectTechnologyId])
REFERENCES [dbo].[ProjectTechnology] ([Id])
GO
ALTER TABLE [dbo].[Project] CHECK CONSTRAINT [FK_Project_ProjectTechnology]
GO
ALTER TABLE [dbo].[Project]  WITH CHECK ADD  CONSTRAINT [FK_Project_ProjectType] FOREIGN KEY([ProjectTypeId])
REFERENCES [dbo].[ProjectType] ([Id])
GO
ALTER TABLE [dbo].[Project] CHECK CONSTRAINT [FK_Project_ProjectType]
GO
USE [master]
GO
ALTER DATABASE [PSAT_Dev] SET  READ_WRITE 
GO
