export const AppConstants = {
    homePage          :'Estimation Dashboard',
    rateCard          :'Resource Rate Card',
    landingPage       :'Landing page',
    effortEstimation  :'Effort Estimation',
    createSOW         :'Create Satement Of Work',
    exportArtifacts   :'View & Export Artifacts',
    timeTracker       :'Presale Time Tracker',
    teamConfiguration :'Team Configuration',
    addRole           :'Add Role',
    capacityUtilization: 'Capacity Utilization',
    ProjectSucessMessage : 'Created SuccessFully',
    ErrorMessage         : 'Something Went Wroung!',
    UpdateSuccsessMessage : 'Details Updated SuccessFully',
    DeleteMessage:  'Deleted SuccessFully',
    role: 'Role',
    user: 'User',
    projecttype: 'Project Types',
  technology: 'Technologies',
}
